In [30]:
import os
import numpy as np
import pandas as pd
import warnings
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [31]:
df=pd.read_csv("C:/..filePath/heart.csv")

In [32]:
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [33]:
df.tail()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [34]:
print('Number of rows are :-',df.shape[0], ',and number of columns are :-',df.shape[1])

Number of rows are :- 303 ,and number of columns are :- 14

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [36]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [37]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [38]:
#counting duplicate 
df.duplicated().sum()

1

In [39]:
df.describe().T

          count        mean        std    min    25%    50%    75%    max
age       303.0   54.366337   9.082101   29.0   47.5   55.0   61.0   77.0
sex       303.0    0.683168   0.466011    0.0    0.0    1.0    1.0    1.0
cp        303.0    0.966997   1.032052    0.0    0.0    1.0    2.0    3.0
trtbps    303.0  131.623762  17.538143   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.264026  51.830751  126.0  211.0  240.0  274.5  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.528053   0.525860    0.0    0.0    1.0    1.0    2.0
thalachh  303.0  149.646865  22.905161   71.0  133.5  153.0  166.0  202.0
exng      303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slp       303.0    1.399340   0.616226    0.0    1.0    1.0    2.0    2.0
caa       303.0    0.729373   1.022606    0.0    0.0    0.0    1.0    4.0
thall     303.0    2.313531   0.612277    0.0    2.0    2.0    3.0    3.0
output    303.0    0.544554   0.498835    0.0    0.0    1.0    1.0    1.0

In [40]:
list_col=['sex','chol','trtbps','cp','thall','exng']

for col in list_col: 
    print('{} :{} ' . format(col.upper(),df[col].unique()))

SEX :[1 0]
CHOL :[233 250 204 236 354 192 294 263 199 168 239 275 266 211 283 219 340 226
 247 234 243 302 212 175 417 197 198 177 273 213 304 232 269 360 308 245
 208 264 321 325 235 257 216 256 231 141 252 201 222 260 182 303 265 309
 186 203 183 220 209 258 227 261 221 205 240 318 298 564 277 214 248 255
 207 223 288 160 394 315 246 244 270 195 196 254 126 313 262 215 193 271
 268 267 210 295 306 178 242 180 228 149 278 253 342 157 286 229 284 224
 206 167 230 335 276 353 225 330 290 172 305 188 282 185 326 274 164 307
 249 341 407 217 174 281 289 322 299 300 293 184 409 259 200 327 237 218
 319 166 311 169 187 176 241 131]
TRTBPS :[145 130 120 140 172 150 110 135 160 105 125 142 155 104 138 128 108 134
 122 115 118 100 124  94 112 102 152 101 132 148 178 129 180 136 126 106
 156 170 146 117 200 165 174 192 144 123 154 114 164]
CP :[3 2 1 0]
THALL :[1 2 3 0]
EXNG :[0 1]

In [41]:
# Özellikler ve etiketleri ayırın
X = df.drop('output', axis=1)
y = df['output']

# Veriyi eğitim ve test setlerine ayırın
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
model_accuracy=[]

## CNN

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# Modeli güncelle
model = Sequential([
    Dense(128, activation='relu', input_dim=X_train.shape[1]),  # Genişletilmiş Giriş katmanı
    Dropout(0.3),
    Dense(64, activation='relu'),  # Genişletilmiş Gizli katman
    Dropout(0.3),
    Dense(64, activation='relu'),  # Yeni Gizli katman
    Dropout(0.3),
    Dense(32, activation='relu'),  # Yeni Gizli katman
    Dropout(0.3),
    Dense(16, activation='relu'),  # Gizli katman
    Dropout(0.3),
    Dense(4, activation='softmax')  # Çıkış katmanı, 4 sınıf için softmax
])

# Modeli derle
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Modeli eğit
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

# Model değerlendirmesi
loss, accuracy = model.evaluate(X_test, y_test)
model_accuracy.append(accuracy)
print(f'Test Accuracy: {accuracy*100:.2f}%')

ModuleNotFoundError: No module named 'distutils'

In [ ]:
from tensorflow.keras.models import Model
# Öznitelik çıkarma modelini oluştur
text_feature_extraction_model = Model(inputs=model.inputs, outputs=model.layers[-2].output)

# Eğitim ve test verilerinden öznitelikleri çıkar
text_features_train = text_feature_extraction_model.predict(X_train)
text_features_test = text_feature_extraction_model.predict(X_test)

# Öznitelik çıkarma sonucunu kontrol etmek için boyutları yazdırma
print("Eğitim verisi öznitelik boyutu:", text_features_train.shape)
print("Test verisi öznitelik boyutu:", text_features_test.shape)

## SVM

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# SVM modelini oluşturma
# SVC, varsayılan olarak RBF kernelini kullanır
svm_model = make_pipeline(StandardScaler(), SVC(kernel='linear', random_state=42))

# Modeli eğitme
svm_model.fit(text_features_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = svm_model.predict(text_features_test)

# Modelin performansını değerlendirme
accuracy = accuracy_score(y_test, y_pred)
model_accuracy.append(accuracy)
print(f'Accuracy: {accuracy*100:.2f}%')

# Ayrıntılı sınıflandırma raporu
print(classification_report(y_test, y_pred))

## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# KNN modelini oluşturma
# n_neighbors parametresi komşu sayısını belirler, varsayılan değer 5'tir.
knn_model = Pipeline([
    ('scaler', StandardScaler()),  # Özellik ölçeklendirme
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

# Modeli eğitme
knn_model.fit(text_features_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = knn_model.predict(text_features_test)

# Modelin performansını değerlendirme
accuracy = accuracy_score(y_test, y_pred)
model_accuracy.append(accuracy)
print(f'Accuracy: {accuracy*100:.2f}%')

# Ayrıntılı sınıflandırma raporu
print(classification_report(y_test, y_pred))

## NB

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Naive Bayes modelini oluşturma
nb_model = Pipeline([
    ('scaler', StandardScaler()),  # Özellik ölçeklendirme
    ('nb', GaussianNB())  # Gaussian Naive Bayes sınıflandırıcısı
])

# Modeli eğitme
nb_model.fit(text_features_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = nb_model.predict(text_features_test)

# Modelin performansını değerlendirme
accuracy = accuracy_score(y_test, y_pred)
model_accuracy.append(accuracy)
print(f'Accuracy: {accuracy*100:.2f}%')

# Ayrıntılı sınıflandırma raporu
print(classification_report(y_test, y_pred))

## LDA

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# LDA modelini oluşturma
lda_model = Pipeline([
    ('scaler', StandardScaler()),  # Özellik ölçeklendirme
    ('lda', LinearDiscriminantAnalysis())  # LDA sınıflandırıcısı
])

# Modeli eğitme
lda_model.fit(text_features_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = lda_model.predict(text_features_test)

# Modelin performansını değerlendirme
accuracy = accuracy_score(y_test, y_pred)
model_accuracy.append(accuracy)
print(f'Accuracy: {accuracy*100:.2f}%')

# Ayrıntılı sınıflandırma raporu
print(classification_report(y_test, y_pred))

## DT

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Karar Ağacı modelini oluşturma
dt_model = Pipeline([
    ('scaler', StandardScaler()),  # Özellik ölçeklendirme
    ('dt', DecisionTreeClassifier(random_state=42))  # Karar Ağacı sınıflandırıcısı
])

# Modeli eğitme
dt_model.fit(text_features_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = dt_model.predict(text_features_test)

# Modelin performansını değerlendirme
accuracy = accuracy_score(y_test, y_pred)
model_accuracy.append(accuracy)
print(f'Accuracy: {accuracy*100:.2f}%')

# Ayrıntılı sınıflandırma raporu
print(classification_report(y_test, y_pred))

## LR

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Lineer Regresyon modelini oluşturma
lr_model = Pipeline([
    ('scaler', StandardScaler()),  # Özellik ölçeklendirme
    ('lr', LinearRegression())  # Lineer Regresyon sınıflandırıcısı
])

# Modeli eğitme
lr_model.fit(text_features_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = lr_model.predict(text_features_test)

# Modelin performansını değerlendirme
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
model_accuracy.append(r2)
print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

In [ ]:
model_name=['CNN','SVM','KNN','NB','LDA','DT','LR']
model_accuracy
df = pd.DataFrame({'Model': model_name, 'Accuracy': model_accuracy})
df

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Grafik boyutunu ayarlama
plt.figure(figsize=(10, 6))

# Seaborn barplot kullanarak görselleştirme
sns.barplot(x='Model', y='Accuracy', data=df)

# Başlık ve eksen etiketlerini ayarlama
plt.title('Model Karşılaştırma')
plt.xlabel('Model')
plt.ylabel('Accuracy (%)')

# Grafiği gösterme
plt.show()